version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/beob-playground
    overwrite: yes
hooks:
  BeforeInstall:
    - location: /scripts/init-docker.sh
      timeout: 60
  AfterInstall:
    - location: /scripts/deploy.sh
      timeout: 30
      runas: root
